# Sử dụng Node.js phiên bản chính thức làm base image
FROM node:14

# Tạo thư mục làm việc trong container
WORKDIR /app

# Sao chép package.json và package-lock.json (nếu có)
COPY package*.json ./

# Cài đặt các dependencies
RUN npm install

# Sao chép toàn bộ mã nguồn của ứng dụng vào container
COPY . .

# Expose cổng mà ứng dụng của bạn chạy (trong trường hợp này là 8000)
EXPOSE 8000

# Khởi động ứng dụng
CMD ["node", "server.js"]